//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.Products_Materials = new HashSet<Products_Materials>();
        }
    
        public int Material_ID { get; set; }
        public string Name { get; set; }
        public int Material_Type_ID { get; set; }
        public int Amount_InPack { get; set; }
        public int Unit_ID { get; set; }
        public int Amount_In_Stock { get; set; }
        public int Min_Possible_Balance { get; set; }
        public int Price { get; set; }
    
        public virtual Material_Type Material_Type { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Materials> Products_Materials { get; set; }
    }
}
