//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Materials
    {
        public int Products_Materials_ID { get; set; }
        public int Product_ID { get; set; }
        public int Material_ID { get; set; }
        public int Necessary_Amount { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
